version: 0.2
  
phases:
  install:
    runtime-versions:
      java: corretto21
      
  build:
    commands:
      - ./gradlew test
  post_build:
    commands:
      - allure generate
      - aws s3 cp allure-report s3://$API_TESTREPORTS_BUCKET --recursive
