version: 0.2
  
phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 24
    commands:
      - wget https://github.com
      - unzip allure-3.0.0.zip -d /opt/
      - ln -s /opt/allure-3/bin/allure /usr/local/bin/allure
      - allure --version

  build:
    commands:
      - ./gradlew test
  post_build:
    commands:
      - allure generate
      - aws s3 cp allure-report s3://$TESTREPORTS_BUCKET --recursive
