version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 24
    commands:
      - npm install allure
      - ln -s /opt/allure-3/bin/allure /usr/local/bin/allure
      - npx allure --version

  build:
    commands:
      - ./gradlew test
  post_build:
    commands:
      - npx allure awesome publication-api/build/allure-results --single-file
      - aws s3 cp allure-report s3://$TESTREPORTS_BUCKET --recursive
