version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 24
    commands:
      - npm install allure@3.8.2
      - npx allure --version

  build:
    commands:
      - ./gradlew test || true
  post_build:
    commands:
      - aws s3 cp s3://$TESTREPORTS_BUCKET/allure-history.jsonl allure-history.jsonl || true
      - npx allure generate "*/build/allure-results"
      - aws s3 cp allure-history.jsonl s3://$TESTREPORTS_BUCKET/allure-history.jsonl
      - aws s3 cp allure-report/index.html s3://$TESTREPORTS_BUCKET/reports/$(date +%Y-%m-%d).html
      - aws s3 cp allure-report s3://$TESTREPORTS_BUCKET --recursive
