version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 24
    commands:
      - npm install allure@3.8.2
      - ln -s /opt/allure-3/bin/allure /usr/local/bin/allure
      - npx allure --version

  build:
    commands:
      - ./gradlew test || true
  post_build:
    commands:
      - mkdir -p allure-results
      - cp */build/allure-results/* allure-results
      - npx allure awesome allure-results --single-file
      - aws s3 cp allure-report s3://$TESTREPORTS_BUCKET --recursive
