plugins {
    id 'nva.api.integration.testing.java-conventions'
}

dependencies {
    api(libs.rest.assured.core)
    api(nvaCatalog.aws.sdk2.regions)
    api(nvaLibs.core)
    implementation('software.amazon.awssdk:apache-client')
    implementation('software.amazon.awssdk:aws-core')
    implementation('software.amazon.awssdk:http-client-spi')
    implementation('software.amazon.awssdk:lambda')
    implementation('software.amazon.awssdk:resourcegroupstaggingapi')
    implementation('software.amazon.awssdk:s3')
    implementation('software.amazon.awssdk:secretsmanager')
    implementation('software.amazon.awssdk:ssm')
    implementation('software.amazon.awssdk:sts')
    implementation(libs.rest.assured.json.path)
    implementation(nvaCatalog.assertj.core)
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.httpcore4)
    runtimeOnly('software.amazon.awssdk:sso')
    runtimeOnly('software.amazon.awssdk:ssooidc')
    runtimeOnly(nvaCatalog.jackson.core)
    runtimeOnly(nvaCatalog.jackson.databind)
    testFixturesApi(libs.rest.assured.core)
    testFixturesImplementation(libs.allure.rest.assured)
    testFixturesImplementation(libs.awaitility.core)
    testFixturesImplementation(nvaCatalog.junit.jupiter.api)
    testFixturesImplementation(nvaCatalog.slf4j.api)
    testFixturesRuntimeOnly(libs.allure.java.commons)
    testFixturesRuntimeOnly(libs.allure.junit5)
    testFixturesRuntimeOnly(nvaCatalog.junit.jupiter.engine)
    testFixturesRuntimeOnly(nvaCatalog.junit.platform.launcher)
    testFixturesRuntimeOnly(nvaCatalog.log4j.core)
    testFixturesRuntimeOnly(nvaCatalog.log4j.slf4j.impl)
}
